
title: powerprove
url: 'http://powerprove.github.io'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Jae Wook Shin  ## put your name
title: 'powerprove'  ## your title
location: null2root


## Social Profiles
facebook: http://powerprove.github.io  ## your facebook account url
twitter: http://powerprove.github.io  ## your twitter account url
linkedin: http://powerprove.github.io  ## your linkedin account url
dribbble: http://powerprove.github.io  ## you dribbble account url
foursquare: http://powerprove.github.io  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
